### PR TITLE
Fix entry project select

### PR DESCRIPTION
**Pull request by lcoq**

### CODE REVIEW

**Comment by lcoq** [comment]
@bobbus here is some fixes on entry project input, would you like to give it a try ?

**Comment by lcoq** [comment]
@bobbus ping. If you don't want to try, maybe merge & deploy directly ?

**Comment by bobbus** [comment]
I was not able to reproduce this bug in dev mode. I wanted to track this bug in production with firebug but as of now without success. If this changes are useful or you think good to merge, ok for merge and deploy.

**Comment by lcoq** [comment]
@bobbus deployed, please create a card on Trello if you have some troubles with projects selection

**Pull request merged**
